version: '3'

services:
  openldap:
    image: zentekmx/openldap:latest
    ports:
    - "389:389"
    volumes:
    - ldap-volume:/var/lib/ldap:Z

  postgres:
    image: postgres:10.1
    ports:
    - "5432:5432"
    volumes:
    - ${POSTGRES_VOLUME:-postgres-volume}:/var/lib/postgresql/data:Z
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}

  redmine:
    image: bitnami/redmine:4
    depends_on:
    - openldap
    - postgres
    ports:
    - "3000:3000"
    volumes:
    - ${REDMINE_VOLUME:-redmine-volume}:/bitnami:Z
    environment:
    - REDMINE_DB_USERNAME=${POSTGRES_USER}
    - REDMINE_DB_PASSWORD=${POSTGRES_PASSWORD}
    - REDMINE_DB_NAME=${POSTGRES_DB}
    - REDMINE_DB_POSTGRES=postgres
    - REDMINE_DB_PORT_NUMBER=5432
    - REDMINE_EMAIL=${REDMINE_EMAIL}
    - REDMINE_USERNAME=${REDMINE_USERNAME}
    - REDMINE_PASSWORD=${REDMINE_PASSWORD}
    - SMTP_HOST=${SMTP_HOST}
    - SMTP_PORT=${SMTP_PORT}
    - SMTP_USER=${SMTP_USER}
    - SMTP_PASSWORD=${SMTP_PASSWORD}

volumes:
    ldap-volume:
    postgres-volume:
    redmine-volume:
